### ISSUE TITLE
EditSession.php has an issues at line 144

### ISSUE THREAD

**Issue by AgentH14** [ShapedBuildingServer/WorldEditOrigin#1]
EditSession.php has an issue at line 144

I cant even join my pocketmine test server with this WorldEdit Plugin...

**Comment by iTCMega** [comment]
what error u got?

**Comment by AgentH14** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/17691461/55672304-8bb0b400-5867-11e9-94f0-cf5ff409b575.png)

I got this message error...

**Comment by AgentH14** [comment]
And heres another error it have me in the Main.php file after you fixed the EditSession.php file

![Screenshot (110)](https://user-images.githubusercontent.com/17691461/55672386-62dcee80-5868-11e9-89b0-41b87a807534.png)

**Comment by iTCMega** [comment]
fixed
